version: "3"
services:
  gpsMicroService:
    image: orionbs/projet8_tourguide_gpsmicroservice
    hostname: gpsservice
    ports:
      - "8081:8081"

  rewardMicroService:
    image: orionbs/projet8_tourguide_rewardmicroservice
    hostname: rewardservice
    ports:
      - "8082:8082"

  tripPricerMicroService:
    image: orionbs/projet8_tourguide_trippricermicroservice
    hostname: trippricerservice
    ports:
      - "8083:8083"

  tourguide:
    image: orionbs/projet8_tourguide
    depends_on:
    	- gpsMicroService
    	- rewardMicroService
    	- tripPricerMicroService
    ports:
      - "8080:8080"
